### ISSUE TITLE
按照安装说明,插件不生效

### ISSUE THREAD

**Issue by baiyimi** [lq782655835/vuepress-plugin-element-ui#1]
vuepress 1.3.1

初始化vuepress项目,启动访问 localhost:8080,it run ok.  Hello VuePress!

然后，按照此插件官网说明，安装并配置 config.js ,plugins
```
module.exports = {
  plugins: ["element-ui"]
};
```
docs/README.md
```
# Hello VuePress!

:::: el-tabs
::: el-tab-pane label=markdown

- vue
  - vue-cli
  - nuxt
  - vuepress
- react
  - create-react-app
  - nest
    :::
    ::: el-tab-pane label=javascript

```javascript
() => {
  console.log("Javascript code example");
};
```

:::
::::

<el-tag>标签一</el-tag>
<el-tag type="success">标签二</el-tag>
<el-tag type="info">标签三</el-tag>
<el-tag type="warning">标签四</el-tag>
<el-tag type="danger">标签五</el-tag>

```
 element-ui 插件未生效．

**Comment by lq782655835** [comment]
看上去是markdown语法没对称。你可以把项目中example的markdown文件整体粘贴到你的项目中试下。
https://raw.githubusercontent.com/lq782655835/vuepress-plugin-element-ui/master/docs/README.md
